transformer:
  output_dim: 3
  d_model: 8
  num_heads: 1
  num_layers: 1
  d_ff: 8
  dropout: 0.1
  num_distribution_layers: 4
  loss_func: "studentT" # Should be Gaussian, MSE, or studentT

train:
  train_split: 0.95
  max_seq_length: 256
  batch_size: 512
  test_batch_size: 512
  total_training_steps: 100000
  early_stopping: 250000
  warmup_steps: 3000
  evaluation_interval: 1000
  test_size: 0.01

datasets:
  monash: # Total: 503,723,130
    - "electricity_hourly_dataset" # 8,443,584
    - "traffic_hourly_dataset"
    - "traffic_weekly_dataset"
    - "solar_4_seconds_dataset"
    - "solar_weekly_dataset"
    - "solar_10_minutes_dataset"
    - "wind_4_seconds_dataset"
    - "oikolab_weather_dataset"
    - "nn5_weekly_dataset"
    - "nn5_daily_dataset_without_missing_values"
    - "cif_2016_dataset"
    - "fred_md_dataset"
    - "hospital_dataset"
    - "m4_hourly_dataset"
    - "electricity_weekly_dataset"
    - "australian_electricity_demand_dataset"
    - "tourism_monthly_dataset"
    - "tourism_quarterly_dataset"
    - "elecdemand_dataset"
    - "sunspot_dataset_without_missing_values"
    # - "wind_farms_minutely_dataset_without_missing_values" # Might be problematic
    # - "london_smart_meters_dataset_with_missing_values" # Might be problematic
    # - "kaggle_web_traffic_dataset_without_missing_values" # Might be problematic Add 455,192,545
  weather: # Total: 1,565,432,018
    - "NOAA_dataset"
    - "ERA5_dataset"
  finance: # 42,578,670
    - "yahoo"
  science:
    - "ZTF"
  audio: # 1,980,610,601
    - "arabic"
    - "commands"
    - "birds"
  energy: # 2,533,584,545
    # - "buildingbench"
  traffic: # 1,507,545,600
    - "CA"