train:
  train_split: 0.95
  max_seq_length: 1024
  batch_size: 512
  test_batch_size: 4096
  total_training_steps: 250000
  early_stopping: 250000
  warmup_steps: 3000
  evaluation_interval: 500

transformer:
  output_dim: 2
  d_model: 8
  num_heads: 1
  num_layers: 1
  d_ff: 8
  dropout: 0.1
  num_distribution_layers: 4
  loss_func: "Gaussian_fixed_var" # Should be Gaussian or Gaussian_fixed_var

datasets:
  - "electricity_hourly_dataset"
  - "traffic_hourly_dataset"
  - "traffic_weekly_dataset"
  - "solar_4_seconds_dataset"
  - "solar_weekly_dataset"
  - "solar_10_minutes_dataset"
  - "wind_4_seconds_dataset"
  - "oikolab_weather_dataset"
  - "nn5_weekly_dataset"
  - "nn5_daily_dataset_without_missing_values"
  - "cif_2016_dataset"
  - "fred_md_dataset"
  - "hospital_dataset"
  - "m4_hourly_dataset"
  - "electricity_weekly_dataset"
  - "australian_electricity_demand_dataset"
  - "tourism_monthly_dataset"
  - "tourism_quarterly_dataset"
  - "elecdemand_dataset"
  - "sunspot_dataset_without_missing_values"
  - "wind_4_seconds_dataset"