#!/bin/bash -l

#SBATCH -J 100M
#SBATCH -t 96:00:00
#SBATCH --qos=qos_gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --mem-per-cpu=3G
#SBATCH --gres=gpu:4
#SBATCH -A tedwar41_gpu
#SBATCH --mail-type=ALL
#SBATCH --mail-user=tedwards2412@gmail.com

conda activate ML
ml cuda/12.1.0

cd /home/tedwar42/TimeTransformers/scripts

python parameter_scaling_training.py configs/parameter_scaling/100M_studentT.yml