#!/bin/bash -l

#SBATCH -J 63M_AR1024
#SBATCH -t 96:00:00
#SBATCH -p amper2
#SBATCH --reservation=cosmicexplorer
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=tedwards2412@gmail.com

ml conda/0.1
ml cuda/11.8
conda activate time

cd /cfs/home/thed7424/TimeTransformers/scripts

python aspectratio_training.py configs/aspectratio_scaling/nparams63M_AR1024.yml