#!/bin/bash -l

#SBATCH --job-name=480k_AR32
#SBATCH --time=72:00:00
#SBATCH --partition=a100
#SBATCH --qos=qos_gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=14
#SBATCH --mem-per-cpu=16G
#SBATCH --gres=gpu:1
#SBATCH -A tedwar41_gpu
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=tedwards2412@gmail.com

conda activate ML
ml cuda/12.1.0

cd /home/tedwar42/TimeTransformers/scripts

python aspectratio_training.py configs/aspectratio_scaling/nparams480k_AR32.yml