#!/bin/bash -l

#SBATCH -J 20M_01p
#SBATCH -t 96:00:00
#SBATCH -p amper2
#SBATCH --reservation=cosmicexplorer
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=tedwards2412@gmail.com

ml conda/0.1
ml cuda/11.8
conda activate time

cd /cfs/home/thed7424/TimeTransformers/scripts

python data_scaling_training.py configs/data_scaling/20M_studentT_datascaling_01p.yml