train:
  train_split: 0.95
  max_seq_length: 1024
  batch_size: 512
  test_batch_size: 4096
  save: False
  total_training_steps: 250000
  early_stopping: 250000
  warmup_steps: 3000

transformer:
  output_dim: 2
  d_model: 8
  num_heads: 1
  num_layers: 1
  d_ff: 8
  dropout: 0.1
  num_distribution_layers: 4
  loss_func: "Gaussian" # Should be Gaussian or Gaussian_fixed_var